IF EXISTS(SELECT 1 FROM master.dbo.sysdatabases WHERE name = 'SPLINEDB')

BEGIN
  print '' print  '*** Dropping database SPLINEDB'
  DROP DATABASE SPLINEDB
END
GO

print '' print '*** Creating database SPLINEDB'
GO
CREATE DATABASE SPLINEDB
GO

print '' print '*** using database SPLINEDB'
GO
USE [SPLINEDB]
GO

print '' print '*** Creating table SPLINE'
CREATE TABLE SPLINE(
	SPLINENAME[NVARCHAR](20),
	USERNAME[NVARCHAR](30),
	COLOR[CHAR](7) DEFAULT '#773399',
	CONSTRAINT [PK_SPLINENAME_USERNAME] PRIMARY KEY([SPLINENAME] ASC, [USERNAME] ASC)
)
GO

print '' print '*** Creating table POINT_INDEX'
CREATE TABLE POINT_INDEX(
	POINT_INDEX_ID[NVARCHAR](5),
	CONSTRAINT [PK_POINT_INDEX_ID] PRIMARY KEY([POINT_INDEX_ID] ASC)
)
GO

print '' print '*** Inserting into POINT_INDEX'
INSERT INTO POINT_INDEX(POINT_INDEX_ID)
VALUES
("ONE"),
("TWO"),
("THREE")
GO

print '' print '*** Creating table POINT'
CREATE TABLE POINT(
	SPLINENAME[NVARCHAR](20),
	USERNAME[NVARCHAR](30),
	POINT_INDEX_ID[NVARCHAR](5),
	X[INT],
	Y[INT],
	Z[INT],
	CONSTRAINT [PK_SPLINENAME_USERNAME_POINT_INDEX_ID] PRIMARY KEY([SPLINENAME] ASC, [USERNAME] ASC, [POINT_INDEX_ID] ASC)
)
GO

print '' print '*** Creating table GUIDE_INDEX'
GO
CREATE TABLE GUIDE_INDEX (
	GUIDE_INDEX_ID[CHAR](3),
	CONSTRAINT [PK_GUIDE_INDEX_ID] PRIMARY KEY([GUIDE_INDEX_ID] ASC)
)
GO

print '' print '*** Inserting into GUIDE_INDEX'
GO
INSERT INTO GUIDE_INDEX (GUIDE_INDEX_ID)
VALUES
("ONE"),
("TWO")
GO

print '' print '*** Creating table GUIDE'
GO
CREATE TABLE GUIDE(
	SPLINENAME[NVARCHAR](20),
	USERNAME[NVARCHAR](30),
	POINT_INDEX_ID[NVARCHAR](5),
	GUIDE_INDEX_ID[CHAR](3),
	A[INT],
	B[INT],
	C[INT],
	CONSTRAINT [PK_SPLINENAME_USERNAME_POINT_INDEX_ID_GUIDE_INDEX_ID] PRIMARY KEY([SPLINENAME] ASC, [USERNAME] ASC, [POINT_INDEX_ID] ASC, [GUIDE_INDEX_ID] ASC)
)
GO

print '' print '*** Creating Foreign Key FK_POINT_SPLINE'
GO
ALTER TABLE [dbo].[POINT] with nocheck
ADD CONSTRAINT [FK_POINT_SPLINE] FOREIGN KEY ([SPLINENAME],[USERNAME])
REFERENCES [dbo].[SPLINE]([SPLINENAME],[USERNAME])
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO

print '' print '*** Creating Foreign Key FK_POINT_POINT_INDEX_ID'
GO
ALTER TABLE [dbo].[POINT]
ADD CONSTRAINT [FK_POINT_POINT_INDEX_ID] FOREIGN KEY ([POINT_INDEX_ID])
REFERENCES [dbo].[POINT_INDEX](POINT_INDEX_ID)
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO

print '' print '*** Creating Foreign Key FK_GUIDE_POINT'
GO
ALTER TABLE [dbo].[GUIDE]
ADD CONSTRAINT [FK_GUIDE_POINT] FOREIGN KEY ([SPLINENAME],[USERNAME],[POINT_INDEX_ID])
REFERENCES [dbo].[POINT]([SPLINENAME], [USERNAME], [POINT_INDEX_ID])
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO

print '' print '*** Creating Foreign Key FK_GUIDE_GUIDE_INDEX_ID'
GO
ALTER TABLE [dbo].[GUIDE]
ADD CONSTRAINT [FK_GUIDE_GUIDE_INDEX_ID] FOREIGN KEY ([GUIDE_INDEX_ID])
REFERENCES [dbo].[GUIDE_INDEX](GUIDE_INDEX_ID)
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO



print '' print '*** Creating procedure bsp_retrieve_user_splines'
GO
CREATE PROCEDURE bsp_retrieve_user_splines (
	@USERNAME[NVARCHAR](30)
)
AS
BEGIN
	SELECT SPLINENAME
	FROM SPLINE
	WHERE USERNAME = @USERNAME
END
GO

print '' print '*** Creating procedure bsp_retrieve_spline_color'
GO
CREATE PROCEDURE bsp_retrieve_spline_color (
	@USERNAME[NVARCHAR](30),
	@SPLINENAME[NVARCHAR](20)
)
AS
BEGIN
	SELECT COLOR
	FROM SPLINE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
END
GO

print '' print '*** Creating procedure bsp_retrieve_spline_points'
GO
CREATE PROCEDURE bsp_retrieve_spline_points (
	@USERNAME[NVARCHAR](30),
	@SPLINENAME[NVARCHAR](20)
)
AS
BEGIN
	SELECT POINT.POINT_INDEX_ID, POINT.X, POINT.Y, POINT.Z, G1.A AS AONE, G1.B AS BONE, G1.C AS CONE, G2.A AS ATWO, G2.B AS BTWO, G2.C AS CTWO
	FROM SPLINE
	INNER JOIN POINT
	ON SPLINE.USERNAME = POINT.USERNAME
	AND SPLINE.SPLINENAME = POINT.SPLINENAME
	INNER JOIN GUIDE G1
	ON G1.USERNAME = POINT.USERNAME
	AND G1.SPLINENAME = POINT.SPLINENAME
	AND POINT.POINT_INDEX_ID = G1.POINT_INDEX_ID
	INNER JOIN GUIDE G2
	ON G2.USERNAME = POINT.USERNAME
	AND G2.SPLINENAME = POINT.SPLINENAME
	AND POINT.POINT_INDEX_ID = G2.POINT_INDEX_ID
	WHERE SPLINE.USERNAME = @USERNAME
	AND SPLINE.SPLINENAME = @SPLINENAME
	AND G1.GUIDE_INDEX_ID = "ONE"
	AND G2.GUIDE_INDEX_ID = "TWO"
END
GO

print '' print '*** Creating procedure bsp_save_spline'
GO
CREATE PROCEDURE bsp_save_spline
(
	@USERNAME[NVARCHAR](30),
	@SPLINENAME[NVARCHAR](20),
	@COLOR[CHAR](7),
	@X_ONE[INT],
	@Y_ONE[INT],
	@Z_ONE[INT],
	@A_ONE_ONE[INT],
	@B_ONE_ONE[INT],
	@C_ONE_ONE[INT],
	@A_ONE_TWO[INT],
	@B_ONE_TWO[INT],
	@C_ONE_TWO[INT],
	@X_TWO[INT],
	@Y_TWO[INT],
	@Z_TWO[INT],
	@A_TWO_ONE[INT],
	@B_TWO_ONE[INT],
	@C_TWO_ONE[INT],
	@A_TWO_TWO[INT],
	@B_TWO_TWO[INT],
	@C_TWO_TWO[INT],
	@X_THREE[INT],
	@Y_THREE[INT],
	@Z_THREE[INT],
	@A_THREE_ONE[INT],
	@B_THREE_ONE[INT],
	@C_THREE_ONE[INT],
	@A_THREE_TWO[INT],
	@B_THREE_TWO[INT],
	@C_THREE_TWO[INT]
) AS
BEGIN
IF 0=(SELECT COUNT(*) FROM SPLINE WHERE USERNAME=@USERNAME AND SPLINENAME = @SPLINENAME)
BEGIN
	INSERT INTO SPLINE (USERNAME, SPLINENAME, COLOR)
	VALUES (@USERNAME, @SPLINENAME, @COLOR)
	
	INSERT INTO POINT (USERNAME,SPLINENAME,POINT_INDEX_ID,X,Y,Z)
	VALUES
	(@USERNAME,@SPLINENAME,'ONE',@X_ONE,@Y_ONE,@Z_ONE),
	(@USERNAME,@SPLINENAME,'TWO',@X_TWO,@Y_TWO,@Z_TWO),
	(@USERNAME,@SPLINENAME,'THREE',@X_THREE,@Y_THREE,@Z_THREE)
	
	INSERT INTO GUIDE (USERNAME,SPLINENAME,POINT_INDEX_ID,GUIDE_INDEX_ID,A,B,C)
	VALUES
	(@USERNAME,@SPLINENAME,'ONE','ONE',@A_ONE_ONE,@B_ONE_ONE,@C_ONE_ONE),
	(@USERNAME,@SPLINENAME,'ONE','TWO',@A_ONE_TWO,@B_ONE_TWO,@C_ONE_TWO),
	(@USERNAME,@SPLINENAME,'TWO','ONE',@A_TWO_ONE,@B_TWO_ONE,@C_TWO_ONE),
	(@USERNAME,@SPLINENAME,'TWO','TWO',@A_TWO_TWO,@B_TWO_TWO,@C_TWO_TWO),
	(@USERNAME,@SPLINENAME,'THREE','ONE',@A_THREE_ONE,@B_THREE_ONE,@C_THREE_ONE),
	(@USERNAME,@SPLINENAME,'THREE','TWO',@A_THREE_TWO,@B_THREE_TWO,@C_THREE_TWO)
END
ELSE
BEGIN
	UPDATE SPLINE
	SET COLOR = @COLOR
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	
	UPDATE POINT
	SET X = @X_ONE,
	Y = @Y_ONE,
	Z = @Z_ONE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'ONE'
	
	UPDATE POINT
	SET X = @X_TWO,
	Y = @Y_TWO,
	Z = @Z_TWO
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'TWO'
	
	UPDATE POINT
	SET X = @X_THREE,
	Y = @Y_THREE,
	Z = @Z_THREE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'THREE'
	
	UPDATE GUIDE
	SET A = @A_ONE_ONE,
	B = @B_ONE_ONE,
	C = @C_ONE_ONE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'ONE'
	AND GUIDE_INDEX_ID = 'ONE'
	
	UPDATE GUIDE
	SET A = @A_ONE_TWO,
	B = @B_ONE_TWO,
	C = @C_ONE_TWO
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'ONE'
	AND GUIDE_INDEX_ID = 'TWO'
	
	UPDATE GUIDE
	SET A = @A_TWO_ONE,
	B = @B_TWO_ONE,
	C = @C_TWO_ONE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'TWO'
	AND GUIDE_INDEX_ID = 'ONE'
	
	UPDATE GUIDE
	SET A = @A_TWO_TWO,
	B = @B_TWO_TWO,
	C = @C_TWO_TWO
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'TWO'
	AND GUIDE_INDEX_ID = 'TWO'
	
	UPDATE GUIDE
	SET A = @A_THREE_ONE,
	B = @B_THREE_ONE,
	C = @C_THREE_ONE
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'THREE'
	AND GUIDE_INDEX_ID = 'ONE'
	
	UPDATE GUIDE
	SET A = @A_THREE_TWO,
	B = @B_THREE_TWO,
	C = @C_THREE_TWO
	WHERE USERNAME = @USERNAME
	AND SPLINENAME = @SPLINENAME
	AND POINT_INDEX_ID = 'THREE'
	AND GUIDE_INDEX_ID = 'TWO'
	
	
END
END

PRINT '' PRINT '***COMPLETE'
